version: 2
jobs:
 build:
   machine: true
   steps:
     - checkout
     - run:
         name: Store Version and Image name
         command: |
           echo 'export TAG=0.1.${CIRCLE_BUILD_NUM}' >> $BASH_ENV
           echo 'export IMAGE_NAME=raidquaza' >> $BASH_ENV
           echo $CIRCLE_TAG
     # with credentials stored in the UI
     - Build and Push
     - run:
         command: |
           docker build --no-cache -t breedocker/$IMAGE_NAME:$TAG --build-arg tag=${TAG} .
           docker build --no-cache -t breedocker/$IMAGE_NAME:latest --build-arg tag=${TAG} .
           docker login -u="$DOCKER_USER" -p="$DOCKER_PASSWORD"
           docker push breedocker/$IMAGE_NAME:$TAG
           docker push breedocker/$IMAGE_NAME:latest
 build_tag:
   machine: true
   steps:
     # with credentials stored in the UI
     - Build and Push
     - run:
         command: |
           docker build --no-cache -t breedocker/$IMAGE_NAME:$CIRCLE_TAG --build-arg tag=${CIRCLE_TAG} .
           docker login -u="$DOCKER_USER" -p="$DOCKER_PASSWORD"
           docker push breedocker/$IMAGE_NAME:$CIRCLE_TAG
 build-pr:
  machine: true
  steps:
    - checkout
    - run:
        command: |
          docker build --no-cache .
   
         
workflows:
  version: 2
  main:
    jobs:
    - build:
        filters:
          branches:
            only: master
    - build-tags:
        filters:
          tags:
            only: /.*/
    - build-pr:
        filters:
          branches:
            ignore: master
